version: '3'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: always
    networks:
      - lahatrad
    entrypoint: ""
    command: "ollama serve && ollama run llam2"

  app:
    depends_on:
      - ollama
    build: ../
    container_name: app
    env_file:
      - app/docker.env
    restart: on-failure
    networks:
      - lahatrad

networks:
  lahatrad:
